services:
  kestra:
    image: kestra/kestra:latest
    container_name: kestra-demo
    ports:
      - "8080:8080"
    environment:
      KESTRA_SERVER_HOST: kestra
      KESTRA_SERVER_PORT: 8080
      KESTRA_SERVER_BASEURI: /
    command: server local
    volumes:
      - /tmp/kestra-wd:/tmp/kestra-wd:rw
    networks:
      - sdsp-common-services
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  sdsp-common-services:
    name: sdsp-common-services